### ISSUE TITLE
Update for ASP.NET Core

### ISSUE THREAD

**Issue by RemarkLima** [AndrewFreemantle/Gravatar-HtmlHelper#2]
I've made some updates I'd like to push to support ASP.NET Core

**Comment by AndrewFreemantle** [comment]
Thanks for the contribution, I'll review your changes and get back to you

**Comment by RemarkLima** [comment]
As I've played around with .NET core a bit more, I'll give it another go as a TagHelper as that would be the "more natural" choice for this I'd think!

**Comment by AndrewFreemantle** [comment]
I've reviewed your changes, read up on the differences to HtmlHelpers in .Net Core MVC and it seems that they return `HtmlContent` rather than `HtmlString`, which means we can simply return the `TagBuilder` object `imgTag`.

Thanks for the push to create a .Net Core MVC version of the GravatarHtmlHelper  :+1:

(Closed by commit 7036372a493052438854c639356d687b2ecb3058)
